apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/J4N06/Testlab.git
    targetRevision: HEAD
    path: k3s-ansible/manifests/clickhouse
    helm:
      releaseName: clickhouse
      values: |
        image:
          repository: bitnamilegacy/clickhouse
        shards: 1
        replicaCount: 1
        keeper:
          enabled: false
        auth:
          username: default
          password: clickhouse
        persistence:
          enabled: true
          size: 8Gi
        service:
          type: NodePort
          nodePorts:
            http: 30123
            tcp: 30900
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
